name: Deploy Flask App to Elastic Beanstalk

on:
  push:
    branches:
      - main  # jab tu main branch pe push karega tab ye chalega

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # yahi version tu ne Beanstalk me use kiya tha

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip application for deployment
        run: zip -r flask-app.zip . -x "*.git*"

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: flask-beanstalk          # AWS Beanstalk app ka naam
          environment_name: flask-beanstalk-env      # Beanstalk environment ka naam
          region: us-east-1                          # tu jis region me bana raha hai
          version_label: github-${{ github.run_number }}
          deployment_package: flask-app.zip
